{
 "title": "Grafana Cloud Billing/Usage",
 "tags": [
  "billing",
  "grafanacloud"
 ],
 "time": { "from": "now/M", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 15, "x": 0, "y": 0 },
   "options": {
    "content": "## Grafana Cloud Free Usage\n\nPlan Includes: 10,000 Active Series | 50 GB logs | 50 GB traces | 14-day retention | Access for up to 3 team members\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 0 },
   "options": {
    "content": "Get more data, users, longer retention, and advanced features like reporting, authentication and multiple stacks. [Learn more about Grafana Cloud Pro](https://grafana.com/orgs/418342/subscription).\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Usage Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Series",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(grafanacloud_instance_active_series) by (id) * on (id) group_left(name) grafanacloud_instance_info"
    }
   ]
  },
  {
   "title": "Current Logs Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "grafanacloud_org_logs_usage" }
   ]
  },
  {
   "title": "Current Traces Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "grafanacloud_org_traces_usage" }
   ]
  },
  {
   "title": "Active Series",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(grafanacloud_instance_active_series) by (id) * on (id) group_left(name) grafanacloud_instance_info",
     "legendFormat": "Active series"
    },
    {
     "expr": "grafanacloud_org_metrics_included_series",
     "legendFormat": "Included Series"
    }
   ]
  },
  {
   "title": "About Metrics",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "options": {
    "content": "Usage is based on active series. The free plan includes up to 10k active series. [Learn more](https://grafana.com/docs/grafana-cloud/fundamentals/active-series-and-dpm/).\n\nStart scraping metrics in minutes with [Integrations](/a/grafana-easystart-app). You’ll get out of the box dashboards and alerts after installing the Grafana Agent.\n\nFinally, learn how to [control Prometheus metric usage](https://grafana.com/docs/grafana-cloud/metrics-control-usage/control-prometheus-metrics-usage/) and identify high cardinality metrics.\n\nNote: if you move to Grafana Cloud Pro in the future, the billing calculation is based on Total Data Points Per Minute (DPM), which can be found below. [Learn more](https://grafana.com/docs/grafana-cloud/fundamentals/active-series-and-dpm/#billing-calculations).\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Logs Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    { "expr": "grafanacloud_org_logs_usage", "legendFormat": "Logs Usage" },
    {
     "expr": "grafanacloud_org_logs_included_usage",
     "legendFormat": "Included Usage"
    }
   ]
  },
  {
   "title": "About Logs",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
   "options": {
    "content": "Usage is based on GB ingested. The free plan includes up to 50GB/month with 2 week retention.\n\nLearn more about [logging with Loki](https://grafana.com/docs/loki/latest/best-practices/), a horizontally-scalable, highly-available log aggregation system inspired by Prometheus.\n\nGet started now gathering logs via the [Grafana Agent](https://grafana.com/docs/grafana-cloud/quickstart/logs_agent_linuxnode/) or by [running Promtail](https://grafana.com/docs/grafana-cloud/quickstart/logs_promtail_linuxnode/).\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Traces Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    { "expr": "grafanacloud_org_traces_usage", "legendFormat": "Traces Usage" },
    {
     "expr": "grafanacloud_org_traces_included_usage",
     "legendFormat": "Included Usage"
    }
   ]
  },
  {
   "title": "About Traces",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 23 },
   "options": {
    "content": "Usage is based on GB ingested. The free plan includes up to 50GB/month with 2 week retention.\n\nLearn more about [tracing with Tempo](https://grafana.com/docs/tempo/latest/).\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Metrics Instance Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Metrics Active Series",
   "type": "graph",
   "description": "Shows:\n\n- Total active-series per managed Prometheus metrics service (GrafanaCloud Stack).\n\n- Active-series ingested in the Datadog format\n\n- Active-series ingested in the Influx format\n\n- Active-series per installed integration (with default job-name in Agent config)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(grafanacloud_instance_active_series) by (id) * on (id) group_left(name) grafanacloud_instance_info",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "max(grafanacloud_instance_active_datadog_series > 0) by (id) * on (id) group_left(name) grafanacloud_instance_info",
     "legendFormat": "{{name}}: Datadog format"
    },
    {
     "expr": "max(grafanacloud_instance_active_influx_series > 0) by (id) * on (id) group_left(name) grafanacloud_instance_info",
     "legendFormat": "{{name}}: Influx format"
    },
    {
     "expr": "max(grafanacloud_instance_active_integration_series) by (id, integration) * on (id) group_left(name) grafanacloud_instance_info",
     "legendFormat": "{{name}}: {{integration}} intg."
    }
   ]
  },
  {
   "title": "Metrics Ingestion Rate (DPM)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(max(grafanacloud_instance_samples_per_second * 60) by (id) * on(id) group_left(name) grafanacloud_instance_info{type!~\"graphite-shared|graphite\"}) or (max(grafanacloud_instance_samples_per_second{cluster=~\"us-central1|eu-west2|hm-us-east2|hm-us-west2\"} * 60) by (id) * on(id) group_left(name) grafanacloud_instance_info{type=~\"graphite-shared|graphite\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Discarded Metric Samples",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "si:/s" }
   ],
   "targets": [
    {
     "expr": "(sum(max(grafanacloud_instance_samples_discarded_per_second) by (id, reason)) by (id, reason) * on(id) group_left(name) grafanacloud_instance_info{type!~\"graphite-shared|graphite\"}) or (sum(max(grafanacloud_instance_samples_discarded_per_second{cluster=~\"us-central1|eu-west2|hm-us-east2|hm-us-west2\"}) by (id, reason)) by (id, reason) * on(id) group_left(name) grafanacloud_instance_info{type=~\"graphite-shared|graphite\"})",
     "legendFormat": "{{name}} - {{reason}}"
    }
   ]
  },
  {
   "title": "Logs Instance Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Logs Ingestion Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(grafanacloud_logs_instance_bytes_received_per_second) by (id) * on(id) group_left(name) grafanacloud_logs_instance_info",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Ingested Logs by Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time((grafanacloud_logs_instance_bytes_received_per_second * 60)[1d:1m])) by (id) * on(id) group_left(name) grafanacloud_logs_instance_info or vector(0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Discarded Log Samples",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "si:/s" }
   ],
   "targets": [
    {
     "expr": "sum(grafanacloud_logs_instance_samples_discarded_per_second) by (id, reason) * on(id) group_left(name) grafanacloud_logs_instance_info",
     "legendFormat": "{{name}} - {{reason}}"
    }
   ]
  },
  {
   "title": "Traces Instance Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Traces Ingestion Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(grafanacloud_traces_instance_bytes_received_per_second) by (id) * on(id) group_left(name) grafanacloud_traces_instance_info",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Ingested Traces by Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time((grafanacloud_traces_instance_bytes_received_per_second * 60)[1d:1m])) by (id) * on(id) group_left(name) grafanacloud_traces_instance_info or vector(0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Discarded Spans",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "si:/s" }
   ],
   "targets": [
    {
     "expr": "sum(grafanacloud_traces_instance_discarded_spans_total:rate5m) by (id, reason) * on(id) group_left(name) grafanacloud_traces_instance_info",
     "legendFormat": "{{name}} - {{reason}}"
    }
   ]
  }
 ]
}