# yaml-language-server: $schema=../../../../charts/tempo/values.schema.json

traces:
  otlp:
    http:
      enabled: true
      receiverConfig:
        max_request_body_size: 52428800
    grpc:
      enabled: true
      receiverConfig:
        max_recv_msg_size_mib: 50

storage:
  trace:
    backend: s3
    s3:
      endpoint: seaweedfs-s3.o11y-seaweedfs.svc:8333
      access_key: "${S3_ACCESS_KEY}"
      secret_key: "${S3_SECRET_KEY}"
      bucket: tempo-traces
      insecure: true

distributor:
  replicas: 3
  maxUnavailable: 2
  extraArgs:
    - -config.expand-env=true

ingester:
  replicas: 3
  maxUnavailable: 2
  extraArgs:
    - -config.expand-env=true
  persistence:
    enabled: true
    storageClass: openebs-hostpath
    size: "10Gi"

compactor:
  replicas: 1
  extraArgs:
    - -config.expand-env=true

querier:
  replicas: 3
  maxUnavailable: 2
  extraArgs:
    - -config.expand-env=true

queryFrontend:
  replicas: 2
  maxUnavailable: 1
  extraArgs:
    - -config.expand-env=true

gateway:
  enabled: true
  replicas: 2
  extraArgs:
    - -config.expand-env=true

memcached:
  enabled: true
  replicas: 1
  extraArgs: []

metricsGenerator:
  enabled: true
  replicas: 1
  extraArgs:
    - -config.expand-env=true
  persistence:
    enabled: true
    storageClass: openebs-hostpath
    size: "10Gi"
  config:
    processor:
      local_blocks:
        filter_server_spans: false
        flush_to_storage: true
    storage:
      remote_write:
        - url: http://mimir-distributed-gateway.o11y-mimir.svc/api/v1/push
          send_exemplars: true

overrides:
  defaults:
    metrics_generator:
      processors:
        - service-graphs
        - span-metrics
        - local-blocks

minio:
  enabled: false
