# yaml-language-server: $schema=https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json

settings:
  aliasPort: 443
  redirPort: 0
  tlsOffload: "0.0.0.0"
  certUrl: "https://meshcentral.jacobcolvin.com"
  WANonly: true
  allowLoginToken: true
  allowFraming: false
  AgentPong: 300

domains:
  "":
    title: MeshCentral
    title2: Homelab
    newAccounts: false
    authStrategies:
      oidc:
        newAccounts: true
        custom:
          authorities:
            - groups
        groups:
          claim: colvinGroups
          required:
            - meshcentral-admin
            - meshcentral-user
          siteadmin:
            - meshcentral-admin
          sync: true
