# yaml-language-server: $schema=../../../../charts/cilium/values.schema.json

cluster:
  name: main
  id: 2

bpf:
  preallocateMaps: true
  distributedLRU:
    enabled: true
  # https://docs.cilium.io/en/stable/operations/performance/tuning/#ebpf-map-backend-memory
  mapDynamicSizeRatio: 0.02
