# yaml-language-server: $schema=../../../../charts/rustdesk/values.schema.json

controllers:
  hbbs:
    containers:
      hbbs:
        args:
          - -r
          - "rustdesk-hbbr:21117"

service:
  hbbs:
    annotations:
      lbipam.cilium.io/ips: "10.10.40.30"
      external-dns.alpha.kubernetes.io/hostname: "rustdesk-host.jacobcolvin.com"
  hbbr:
    annotations:
      lbipam.cilium.io/ips: "10.10.40.31"
      external-dns.alpha.kubernetes.io/hostname: "rustdesk-relay.cin.macro.network"
