# yaml-language-server: $schema=../../../../charts/rustdesk/values.schema.json

controllers:
  app:
    containers:
      hbbs:
        args:
          - -r
          - "10.10.40.30:21117"

service:
  rustdesk:
    annotations:
      lbipam.cilium.io/ips: "10.10.40.30"
      external-dns.alpha.kubernetes.io/hostname: "rustdesk-host.jacobcolvin.com"
