# yaml-language-server: $schema=../../../../charts/meshcentral/values.schema.json

controllers:
  app:
    annotations:
      reloader.stakater.com/auto: "true"
    replicas: 1
    strategy: Recreate
    containers:
      meshcentral:
        image:
          repository: ghcr.io/ylianst/meshcentral
          tag: "1.1.58"
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        probes:
          startup:
            enabled: true
            type: TCP
            port: 4430
            spec:
              failureThreshold: 30
              periodSeconds: 5
          liveness:
            enabled: true
            type: TCP
            port: 4430
          readiness:
            enabled: true
            type: TCP
            port: 4430

service:
  app:
    ports:
      https:
        port: 4430

persistence:
  data:
    type: persistentVolumeClaim
    storageClass: openebs-hostpath
    accessMode: ReadWriteOnce
    size: 5Gi
    globalMounts:
      - path: /opt/meshcentral/meshcentral-data
  files:
    type: persistentVolumeClaim
    storageClass: openebs-hostpath
    accessMode: ReadWriteOnce
    size: 10Gi
    globalMounts:
      - path: /opt/meshcentral/meshcentral-files
  config:
    type: secret
    name: meshcentral-config
    globalMounts:
      - subPath: config.json
        path: /opt/meshcentral/meshcentral-data/config.json
        readOnly: true
  certs:
    type: secret
    name: meshcentral-certs
    defaultMode: 256
    globalMounts:
      - subPath: root-cert-public.crt
        path: /opt/meshcentral/meshcentral-data/root-cert-public.crt
        readOnly: true
      - subPath: root-cert-private.key
        path: /opt/meshcentral/meshcentral-data/root-cert-private.key
        readOnly: true
      - subPath: agentserver-cert-public.crt
        path: /opt/meshcentral/meshcentral-data/agentserver-cert-public.crt
        readOnly: true
      - subPath: agentserver-cert-private.key
        path: /opt/meshcentral/meshcentral-data/agentserver-cert-private.key
        readOnly: true
      - subPath: webserver-cert-public.crt
        path: /opt/meshcentral/meshcentral-data/webserver-cert-public.crt
        readOnly: true
      - subPath: webserver-cert-private.key
        path: /opt/meshcentral/meshcentral-data/webserver-cert-private.key
        readOnly: true
      - subPath: mpsserver-cert-public.crt
        path: /opt/meshcentral/meshcentral-data/mpsserver-cert-public.crt
        readOnly: true
      - subPath: mpsserver-cert-private.key
        path: /opt/meshcentral/meshcentral-data/mpsserver-cert-private.key
        readOnly: true
      - subPath: codesign-cert-public.crt
        path: /opt/meshcentral/meshcentral-data/codesign-cert-public.crt
        readOnly: true
      - subPath: codesign-cert-private.key
        path: /opt/meshcentral/meshcentral-data/codesign-cert-private.key
        readOnly: true
