{
 "title": "pfSense Network Quality",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "ping_maximum_response_ms",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max_over_time(ping_maximum_response_ms[$__interval])",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "ping_standard_deviation_ms",
   "type": "candlestick",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(ping_average_response_ms) + (sum(ping_standard_deviation_ms) / 2)",
     "legendFormat": "high"
    },
    {
     "expr": "(sum(ping_average_response_ms) - (sum(ping_standard_deviation_ms)) / 2) > 0 or vector(0)",
     "legendFormat": "low"
    },
    { "expr": "sum(ping_maximum_response_ms)", "legendFormat": "max" },
    { "expr": "sum(ping_minimum_response_ms)", "legendFormat": "min" }
   ]
  },
  {
   "title": "dns_query_query_time_ms",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max_over_time(dns_query_query_time_ms[$__interval])",
     "legendFormat": "{{ server }} {{ record_type }}"
    }
   ]
  },
  {
   "title": "ping_percent_packet_loss",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(ping_percent_packet_loss[$__interval])",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "net_drop /s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(net_drop_out{job=\"pfsense-telegraf\"}[$__rate_interval]) != 0",
     "legendFormat": "out {{ interface }}"
    },
    {
     "expr": "rate(net_drop_in{job=\"pfsense-telegraf\"}[$__rate_interval]) != 0",
     "legendFormat": "in {{ interface }}"
    }
   ]
  },
  {
   "title": "net_err /s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(net_err_out{job=\"pfsense-telegraf\"}[$__rate_interval]) != 0",
     "legendFormat": "out {{ interface }}"
    },
    {
     "expr": "rate(net_err_in{job=\"pfsense-telegraf\"}[$__rate_interval]) != 0",
     "legendFormat": "in {{ interface }}"
    }
   ]
  }
 ]
}