# yaml-language-server: $schema=../../../../charts/volsync/values.schema.json

metrics:
  disableAuth: true

resources:
  requests:
    cpu: "100m"
    memory: "64Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"
