# yaml-language-server: $schema=../../../../charts/external_secrets/values.schema.json

# Single node: one replica each, no leader election.
replicaCount: 1
leaderElect: false

webhook:
  replicaCount: 1

certController:
  replicaCount: 1
