# yaml-language-server: $schema=../../../../charts/seaweedfs/values.schema.json

master:
  nodeSelector: &nodeSelector |
    kubernetes.io/hostname: knas01
  tolerations: &tolerations |
    - key: "node-role.kubernetes.io/storage"
      effect: "NoSchedule"

filer:
  nodeSelector: *nodeSelector
  tolerations: *tolerations

volume:
  nodeSelector: *nodeSelector
  tolerations: *tolerations
