# yaml-language-server: $schema=../../../../charts/k8s_monitoring/values.schema.json

destinations:
  loki:
    type: loki
  tempo:
    type: otlp
    protocol: http
    traces:
      enabled: true
    metrics:
      enabled: false
    logs:
      enabled: false
  mimir:
    type: prometheus

collectors:
  alloy-metrics:
    presets: [clustered, statefulset]
  alloy-logs:
    presets: [filesystem-log-reader, daemonset]
  alloy-singleton:
    presets: [singleton]
  alloy-receiver:
    presets: [deployment]

prometheusOperatorObjects:
  enabled: true
  collector: alloy-singleton

clusterMetrics:
  enabled: true
  collector: alloy-metrics
  apiServer:
    enabled: true
  kubeControllerManager:
    enabled: true
  kubeScheduler:
    enabled: true

hostMetrics:
  enabled: true
  collector: alloy-metrics
  linuxHosts:
    enabled: true

telemetryServices:
  kube-state-metrics:
    deploy: true
  node-exporter:
    deploy: true

clusterEvents:
  enabled: true
  collector: alloy-singleton

annotationAutodiscovery:
  enabled: true
  collector: alloy-metrics

podLogsViaLoki:
  enabled: true
  collector: alloy-logs

applicationObservability:
  enabled: true
  collector: alloy-receiver
  receivers:
    otlp:
      grpc:
        enabled: true
        port: 4317
      http:
        enabled: true
        port: 4318

autoInstrumentation:
  enabled: true
  collector: alloy-metrics

integrations:
  collector: alloy-singleton
  alloy:
    instances:
      - name: alloy-metrics
        labelSelectors:
          app.kubernetes.io/name: alloy-metrics
      - name: alloy-logs
        labelSelectors:
          app.kubernetes.io/name: alloy-logs
      - name: alloy-singleton
        labelSelectors:
          app.kubernetes.io/name: alloy-singleton
      - name: alloy-receiver
        labelSelectors:
          app.kubernetes.io/name: alloy-receiver
