# yaml-language-server: $schema=../../../../charts/k8s_monitoring/values.schema.json

destinations:
  loki:
    type: loki
  tempo:
    type: otlp
    protocol: http
    traces:
      enabled: true
    metrics:
      enabled: false
    logs:
      enabled: false
  mimir:
    type: prometheus

prometheusOperatorObjects:
  enabled: true
  crds:
    deploy: true

clusterMetrics:
  enabled: true
  apiServer:
    enabled: true
  kubeControllerManager:
    enabled: true
  kubeScheduler:
    enabled: true

clusterEvents:
  enabled: true

podLogsViaLoki:
  enabled: true

applicationObservability:
  enabled: true
  receivers:
    otlp:
      grpc:
        enabled: true
        port: 4317
      http:
        enabled: true
        port: 4318

autoInstrumentation:
  enabled: true

integrations:
  alloy:
    instances:
      - name: alloy
